name: SVGO CI
env:
  FORCE_COLOR: 2
  NODE: 20
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: blacksmith-staging
    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ env.NODE }}
          cache: yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
  regression:
    name: Test regressions
    runs-on: blacksmith-staging
    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ env.NODE }}
          cache: yarn
      - run: yarn install
      - run: yarn playwright install --with-deps chromium
      - run: yarn test-regression
  test:
    name: ${{ matrix.os }} Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 18
          - 16
        os:
          - blacksmith-staging
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
      - run: yarn playwright install --with-deps chromium
      - run: yarn test
      - run: yarn test-bundles
